### ISSUE TITLE
Reorder sections

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/firefox-health-dashboard#625] opened 2019-12-11 17:23 UTC
The summary sections should be reordered for ease of use:

* code pageload
* startup from homescreen
* startup from applink
* speedometer score
* dropped frame
* power use

**Comment by divyanshu-rawat** [comment] 2019-12-17 22:33
@klahnakoski I can work on this let me know if it is up for grab?

**Comment by klahnakoski** [comment] 2019-12-18 10:28
@divyanshu-rawat yes, please

**Comment by divyanshu-rawat** [comment] 2019-12-18 10:52
@klahnakoski could you please give more info. on it where exactly is the summer section 👍

**Comment by klahnakoski** [comment] 2019-12-18 11:00
@divyanshu-rawat 

There is a windows (aka quantum) and android summary sections:  

https://health.graphics/android
https://health.graphics/quantum/64
https://health.graphics/quantum/32

**Comment by divyanshu-rawat** [comment] 2019-12-18 19:16
@klahnakoski do you mean these sections?
if yes then where is `speedometer score `section?

<img width="273" alt="Screenshot 2019-12-18 at 20 15 37" src="https://user-images.githubusercontent.com/13464678/71115842-2e7d4880-21d3-11ea-8c54-4977810bb422.png">

**Comment by klahnakoski** [comment] 2019-12-19 00:34
@divyanshu-rawat no.  these sections...

![image](https://user-images.githubusercontent.com/2334429/71134739-684b5080-21cd-11ea-81e3-00dff0f4f289.png)

**Comment by klahnakoski** [comment] 2019-12-19 00:36
they are called "sections" in the code

**Comment by klahnakoski** [comment] 2020-01-21 15:43
@divyanshu-rawat   Are you still on this?

**Comment by divyanshu-rawat** [comment] 2020-01-22 11:59
@klahnakoski yes I am working on it need some time will get back to you 👍

**Comment by divyanshu-rawat** [comment] 2020-02-11 08:59
> The summary sections should be reordered for ease of use:
> 
> * code pageload
> * startup from homescreen
> * startup from applink
> * speedometer score
> * dropped frame
> * power use

Sorry for delay in the woking in the issue, @klahnakoski I was working on something else I have few doubts regarding the issue as its been long since I was working on it.

Queries:
1 - Issue says reorder the sections, reorder means changing the order of sections, but there are no existing sections named as 

* code pageload
* startup from homescreen
* startup from applink
* speedometer score
* dropped frame
* power use

so it is renaming the sections or reordering?


2 - windows sections are defined here s`rc/windows/Windows.jsx` in a `const sections =    [{
        title: 'Benchmarks', ... `}, {}, ...];

so sections has to be renamed then in what manner what should I rename benchmarks to ? and if they need to be reordered how should new order looks like?


3 - React dev tools at `http://localhost:5000/android` shows indicates `Bugzilla`, `NimbledroidFirefox`, `Github`, `Raptor (TP6m)`,  `Media Playback - Firefox Preview`, `Perfherder` as sections
<img width="1456" alt="Screenshot 2020-02-11 at 09 52 30" src="https://user-images.githubusercontent.com/13464678/74222289-72ad3680-4cb4-11ea-93c4-42e7a3cb9f4c.png">

so if they are sections and they needs to reordered then what should be the new order look like, and what this below mentioned sections are?

* code pageload
* startup from homescreen
* startup from applink
* speedometer score
* dropped frame
* power use


Let me know your thoughts on my queries :).

**Comment by divyanshu-rawat** [comment] 2020-03-03 10:24
@klahnakoski I think you might have missed the message :)

**Comment by klahnakoski** [comment] 2020-03-04 21:36
Yes, sorry I missed that last message.

I see that my list of sections in this issue do not match the section names in the code.  Plus, "startup from ..." do not even exist.  

For each section name I used in this issue:
* find a hint as to which of the visual sections it is referring to.
* find the code that refers to the same visual section
* cut-and-paste the code so the order is as correct as possible
* the extra sections will be in the same order, at the bottom

Make some guesses, submit a PR, and then we can discuss specifics.

**Comment by sabina-rohman** [comment] 2020-03-05 17:40
Hi, @klahnakoski  I'm an outreachy applicant May 2020. Can I please work on this issue, if it's still open?

**Comment by klahnakoski** [comment] 2020-03-05 18:10
@sabina-rohman I believe @divyanshu-rawat  is working on this.

**Comment by rimshach** [comment] 2020-03-05 18:25
Hey @klahnakoski if the issue is not assigned to anyone , can I work on this issue?

**Comment by klahnakoski** [comment] 2020-03-05 18:27
@rimshach   I believe @divyanshu-rawat is working on this.

**Comment by kimberlythegeek** [comment] 2020-03-06 16:47
Hi @sabina-rohman and @rimshach ! I am the other mentor for the Outreachy project--feel free to reach out with any questions you may have, as well as request code reviews from me. 

I realize there are not many open issues for this dashboard, but you can also make contributions to [Perfherder](https://treeherder.mozilla.org/perf.html#/alerts?hideDwnToInv=1), another react dashboard. This is outside the scope of the internship, but there are many more issues available to work on.

https://bugzilla.mozilla.org/buglist.cgi?product=Tree%20Management&component=Perfherder&resolution=---&list_id=15132483

**Comment by rimshach** [comment] 2020-03-06 17:01
Hey Kimberly,
Thankyou for the guidance,After looking at the number of open issues,I
started looking at other projects as well,I have started working on one of
them for now.

Regards,
Rimsha Chaudhry

**Comment by kimberlythegeek** [comment] 2020-03-06 17:03
Of course! Feel free to reach out at any time if you still have interest in my project. Best of luck!

Kimberly 



Kimberly Sereduck
Software Engineer in Test
Mozilla Corporation
kimberlythegeek@mozilla.com <mailto:kimberlythegeek@mozilla.com>

**Closed** 2021-04-19 13:07 UTC
Labels: enhancement, good first issue
