### ISSUE TITLE
Migrate browsertime metrics in the dashboard to *SI

### ISSUE THREAD

**Issue by jesup** [mozilla-frontend-infra/firefox-health-dashboard#704] opened 2020-06-18 18:19 UTC
We should be monitoring one of the SI variants (SI, CSI, PSI or a geomean of the 3, though they're highly correlated) instead of loadtime, for all metrics based on browsertime.   (which should eventually be all of them).

**Comment by davehunt** [comment] 2020-06-18 19:16
@jesup Currently the summary pages use load time. which of the SI variants should we use here?

For the detailed view, I propose we refactor the 'tests' dropdown from the following values:
* Warm first-blank paint
* Warm load time
* Wam DOM content flushed
* Warm time to first interactive
* Cold first-blank paint
* Cold load time
* Cold DOM content flushed
* Cold time to first interactive

To something like (thoughts on what to include?):
* SpeedIndex
* Load time
* DOM content flushed
* Time to first interactive

With a new dropdown with:
* Cold
* Warm

**Comment by davehunt** [comment] 2020-06-18 19:17
It looks like this might be a duplicate of #663 but that appears to have stalled. @airimovici @kimberlythegeek should we close that bug and continue here?

**Comment by jesup** [comment] 2020-10-14 15:26
I'd keep first-blank-paint, otherwise looks good.  I'd even be happy with keeping one dropdown with warm/cold versions if that's simpler

**Closed** 2021-04-19 13:07 UTC
Labels: P2, enhancement, performance-team
